name: Swiss
favicon: null
layout_spectrum: 0.2955231452360749
typography_spectrum: 0.3133833375759423
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.13792185299098492
  lightness: 0.5843336612451822
  saturation: 0.32877085101790726
  rhythmicContrast: 0.8093810533173382
purpose: []
